version: "3.7"

services:
  spendbase_home_task_server:
    container_name: "spendbase-home-task-service"
    build:
      context: .
    command: npm run start:dev
    volumes:
      - .:/opt/node_app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:pass@spendbase_home_task_psql:5432/postgres
      PORT: 6001
    ports:
      - "6010:6001"
    depends_on:
      - spendbase_home_task_psql

  spendbase_home_task_psql:
    container_name: "spendbase-home-task-psql"
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5410:5432

volumes:
  spendbase-home-task:
